/* eslint-disable import/prefer-default-export */
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER = 'LOGIN_USER ';
export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const GET_REDFLAGS_SUCCESS = 'GET_REDFLAGS_SUCCESS';
export const GET_REDFLAGS_FAILURE = 'GET_REDFLAGS_FAILURE';
